const model = require('../lib/ai');
const Memory = require('../models/Memory');
const ChatLog = require('../models/ChatLog');
const config = require('../config');
const logger = require('../lib/logger');
const react = require('../lib/react');
const RateLimiter = require('../lib/rateLimiter');
const downloadMedia = require('../lib/downloadMedia');

// Rate limit: 5 AI requests per minute per user
const aiLimiter = new RateLimiter(60000, 5);

// Ambil nama bot dari config, atau default 'AI' kalau gak ada
const botSignature = `_Generated by ${config.botName || 'AI'}_`;

// ============================================================
// 🕵️‍♂️ 1. OBSERVER (MATA-MATA PEKA TANGGAL)
// ============================================================
const observe = async (client, msg, namaPengirim) => {
    const text = msg.body;

    // 🔥 FILTER KHUSUS: CEK WATERMARK BOT (ANTI-LOOP)
    if (text.includes(botSignature)) return;

    // --- LAYER 0: PRE-CHECK ---
    if (text.startsWith('!') || text.length < 5) return;
    const blacklist = ['bot', 'menu', 'error', 'system', 'reset', 'admin'];
    if (blacklist.some(w => text.toLowerCase().includes(w))) return;

    // --- LAYER 1: TRIGGER WORDS ---
    const triggers = [
        'nama', 'panggil', 'tinggal', 'kerja', 'sekolah', 'kuliah',
        'pacar', 'pasangan', 'istri', 'suami', 'nikah', 'jadian', 'mantan', 'tunangan',
        'tanggal', 'hari', 'lahir', 'ultah', 'ulang tahun', 'anniv', 'anniversary', 'kapan',
        'suka', 'cinta', 'benci', 'gasuka', 'hobi', 'favorit', 'gemar', 'takut', 'alergi',
        'rencana', 'niat', 'mau', 'pengen', 'akan', 'bakal', 'besok', 'lusa'
    ];

    if (!triggers.some(w => text.toLowerCase().includes(w))) return;

    // 👇 LOG YANG LU CARI
    logger.debug(`[OBSERVER] Kandidat Memori: "${text.slice(0, 30)}..."`);

    // --- LAYER 2: AI VALIDATION ---
    try {
        const today = new Date().toLocaleDateString('id-ID', {
            weekday: 'long', year: 'numeric', month: 'long', day: 'numeric'
        });

        const prompt = `
        Bertindaklah sebagai 'Memory Keeper' yang sangat selektif.
        User: ${namaPengirim}
        Waktu: ${today}
        Chat: "${text}"

        Tugas: Ekstrak FAKTA PENTING (Biografi/Relasi/Preferensi/Rencana) dalam 1 kalimat (Sudut pandang ke-3).
        
        [ATURAN]
        - SIMPAN: Fakta permanen, Tanggal penting, Rencana konkret.
        - BUANG: Basa-basi, Perasaan sesaat, Pertanyaan ke bot.
        
        Jika tidak layak simpan, jawab persis "SKIP".
        `;

        const result = await model.generateContent(prompt);
        const fact = result.response.text().trim();

        if (fact.toUpperCase().includes('SKIP')) return;

        // Simpan ke Database
        await Memory.add(namaPengirim, fact);

        // 👇 LOG SUKSES DISIMPAN
        logger.info(`[MEMORY SAVED] User: ${namaPengirim} | Fakta: ${fact}`);

        // Lapor ke Owner (Jika bukan dari owner sendiri)
        if (config.system && config.system.logNumber) {
            client.sendMessage(config.system.logNumber,
                `📝 *INGATAN BARU TERCIPTA*\n👤 ${namaPengirim}\n🧠 ${fact}`
            ).catch(() => { });
        }

    } catch (err) {
        logger.error("Observer Error:", err.message);
    }
};

// ============================================================
// 🤖 2. INTERACT (HANDLING COMMAND)
// ============================================================
const interact = async (client, msg, args, senderId, namaPengirim, text) => {
    const command = args[0].toLowerCase();
    const content = text.replace(command, '').trim();

    // --- A. COMMAND !setpersona ---
    if (command === '!setpersona') {
        if (!content) return msg.reply("Mana personanya? Contoh: `!setpersona Kamu adalah dokter.`");
        await Memory.setPersona(content);
        return msg.reply("✅ Persona updated!");
    }

    // --- B. COMMAND !ingat ---
    if (command === '!ingat') {
        if (!content) return msg.reply("Contoh: `!ingat Dini ultah 5 Mei.`");
        await Memory.add(namaPengirim, `[Manual] ${content}`);
        return msg.reply("✅ Tersimpan.");
    }

    // --- C. COMMAND !ai / !analisa ---
    if (command === '!ai' || command === '!analisa' || command === '!tanya') {

        // Rate limit check
        if (!aiLimiter.check(senderId)) {
            return msg.reply("⏳ Terlalu banyak request AI. Tunggu sebentar.");
        }

        const hasMedia = msg.hasMedia;
        const hasQuotedMedia = msg.hasQuotedMsg && (await msg.getQuotedMessage()).hasMedia;

        if (!content && !hasMedia && !hasQuotedMedia) {
            return msg.reply("Mau nanya apa? (Kirim teks atau gambar)");
        }

        await react(msg, '👀');

        try {
            let quotedText = "";
            if (msg.hasQuotedMsg) {
                // Ambil pesan asli yang lagi di-reply
                const quotedMsg = await msg.getQuotedMessage(); 
                
                // Kalau pesan yang di-reply ada teksnya, simpan buat dikasih ke AI
                if (quotedMsg.body) {
                    quotedText = `\n[KONTEKS TAMBAHAN - User me-reply pesan ini]:\n"${quotedMsg.body}"\n`;
                }
            }

            let userPrompt = content;
            if (!userPrompt && (hasMedia || hasQuotedMedia)) {
                userPrompt = "Deskripsikan gambar ini secara detail. Apa yang kamu lihat?";
            }

            const persona = await Memory.getPersona();
            const memories = await Memory.getByUser(namaPengirim, 20);
            const chatHistory = await ChatLog.getHistory(20);
            const memText = memories.map(m => `- ${m.fakta}`).join('\n');
            const today = new Date().toLocaleDateString('id-ID', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });

            const finalPrompt = `
            [SYSTEM]
            Persona: ${persona}
            Waktu: ${today}
            Lawan Bicara: ${namaPengirim}
            
            [INGATAN]
            ${memText || '(Kosong)'}
            
            [CHAT TERAKHIR]
            ${chatHistory}
            ${quotedText}
            User: "${userPrompt}"
            Jawab natural & santai.
            `;

            let payload = [finalPrompt];

            let mediaData = null;
            if (hasMedia) {
                mediaData = await downloadMedia(msg);
            } else if (hasQuotedMedia) {
                const quotedMsg = await msg.getQuotedMessage();
                mediaData = await downloadMedia(quotedMsg);
            }

            if (mediaData) {
                if (mediaData.mimetype.startsWith('image/')) {
                    payload.push({ inlineData: { data: mediaData.data, mimeType: mediaData.mimetype } });
                } else {
                    return msg.reply("❌ Maaf, saat ini mata gw cuma bisa liat *GAMBAR* (JPG/PNG).");
                }
            }

            const result = await model.generateContent(payload);
            let reply = result.response.text().replace(/^(Bot|AI):/i, '').trim();

            reply += `\n\n${botSignature}`;

            await react(msg, '✅');
            msg.reply(reply);

        } catch (e) {
            logger.error("AI Interact Error:", e);
            msg.reply("❌ Otak lagi konslet bang. Coba lagi nanti.");
        }
    }
};

module.exports = { observe, interact };

module.exports.metadata = {
    category: "AI",
    commands: [
        { command: '!ai', desc: 'Chat AI' },
        { command: '!analisa', desc: 'Analisa Gambar' },
        { command: '!ingat', desc: 'Simpan memori manual' },
        { command: '!setpersona', desc: 'Set karakter bot' }
    ]
};