const fs = require('fs');
const path = require('path');

module.exports = async (client, msg, args, senderId, namaPengirim, text) => {
    const chatDestination = msg.fromMe ? msg.to : msg.from;
    const command = args[0]; // !menu, !ping, dll

    // --- FITUR 1: CEK ID (!CEKID) ---
    if (command === '!cekid') {
        return client.sendMessage(chatDestination, `🆔 ID Terdeteksi: \`${senderId}\`\n👤 User: ${namaPengirim || 'Gak Dikenal'}`);
    }

    if (command === '!ping') {
        return client.sendMessage(chatDestination, "Pong!");
    }

    // --- FITUR 2: MENU OTOMATIS (!HELP / !MENU) ---
    if (command === '!help' || command === '!menu') {
        let menuText = `🤖 *MENU BOT PINTAR* 🤖\n_Auto-Generated by System_\n\n`;

        // 1. KAMUS UTAMA ICON
        const fixedIcons = {
            'KEUANGAN': '💰', 'AI': '🧠', 'DOWNLOADER': '📥',
            'MEDIA': '🎬', 'EVENT': '🗓️', 'SYSTEM': '⚙️',
            'GROUP': '👥', 'ADMIN': '🛡️'
        };

        // 2. FUNGSI PENEBAK ICON (Smart Detect)
        const getSmartIcon = (categoryName) => {
            const cat = categoryName.toUpperCase();
            if (fixedIcons[cat]) return fixedIcons[cat];
            if (cat.includes('GAME') || cat.includes('FUN')) return '🎮';
            if (cat.includes('TOOL') || cat.includes('UTIL')) return '🛠️';
            if (cat.includes('INFO') || cat.includes('NEWS')) return 'ℹ️';
            if (cat.includes('STICKER') || cat.includes('STIKER')) return '🎨';
            return '📂';
        };

        // 3. BACA COMMANDS
        const commandFiles = fs.readdirSync(__dirname).filter(file => file.endsWith('.js'));
        const categories = {};

        for (const file of commandFiles) {
            try {
                const cmdModule = require(path.join(__dirname, file));
                if (cmdModule.metadata) {
                    const meta = cmdModule.metadata;
                    if (!categories[meta.category]) categories[meta.category] = [];
                    meta.commands.forEach(c => {
                        categories[meta.category].push(`- *${c.command}* : ${c.desc}`);
                    });
                }
            } catch (err) { console.error(`Skip ${file}:`, err); }
        }

        // 4. RAKIT TEXT (Prioritas Urutan)
        const priorityOrder = ['KEUANGAN', 'DOWNLOADER', 'MEDIA', 'AI', 'EVENT', 'SYSTEM', 'LAINNYA'];

        priorityOrder.forEach(cat => {
            if (categories[cat]) {
                const icon = getSmartIcon(cat);
                menuText += `${icon} *${cat}*\n${categories[cat].join('\n')}\n\n`;
                delete categories[cat];
            }
        });

        for (const cat in categories) {
            const icon = getSmartIcon(cat);
            menuText += `${icon} *${cat}*\n${categories[cat].join('\n')}\n\n`;
        }

        menuText += `_Gunakan dengan bijak ya Bang ${namaPengirim}!_ ☕`;
        return client.sendMessage(chatDestination, menuText);
    }
};

module.exports.metadata = {
    category: "SYSTEM",
    commands: [
        { command: '!menu', desc: 'Menu Otomatis' },
        { command: '!cekid', desc: 'Cek ID & Info' },
        { command: '!ping', desc: 'Tes Respon' }
    ]
};