const fs = require('fs');
const path = require('path');

module.exports = async (client, msg, text, senderId, namaPengirim) => {
    const chatDestination = msg.fromMe ? msg.to : msg.from;

    // --- FITUR 1: CEK ID (!CEKID) ---
    if (text === '!cekid') {
        return client.sendMessage(chatDestination, `🆔 ID Terdeteksi: \`${senderId}\`\n👤 User: ${namaPengirim || 'Gak Dikenal'}`);
    }

    if (text === '!ping') {
        return client.sendMessage(chatDestination, "Pong!");
    }

    // --- FITUR 2: MENU OTOMATIS (!HELP / !MENU) ---
    if (text === '!help' || text === '!menu') {
        let menuText = `🤖 *MENU BOT PINTAR* 🤖\n_Auto-Generated by System_\n\n`;

        // 1. KAMUS UTAMA ICON (Yang Pasti-Pasti Aja)
        const fixedIcons = {
            'KEUANGAN': '💰',
            'AI': '🧠',
            'DOWNLOADER': '📥',
            'MEDIA': '🎬',       // 👈 Request lu tadi
            'EVENT': '🗓️',
            'SYSTEM': '⚙️',
            'GROUP': '👥',
            'ADMIN': '🛡️'
        };

        // 2. FUNGSI PENEBAK ICON (Biar Dinamis) 🧠
        const getSmartIcon = (categoryName) => {
            const cat = categoryName.toUpperCase();

            // Cek Kamus Utama dulu
            if (fixedIcons[cat]) return fixedIcons[cat];

            // Cek Keyword (Kalau kategori baru mengandung kata ini)
            if (cat.includes('GAME') || cat.includes('FUN')) return '🎮';
            if (cat.includes('TOOL') || cat.includes('UTIL')) return '🛠️';
            if (cat.includes('INFO') || cat.includes('NEWS')) return 'ℹ️';
            if (cat.includes('STICKER') || cat.includes('STIKER')) return '🎨';
            if (cat.includes('ISLAM') || cat.includes('RELIGI')) return '🕌';
            if (cat.includes('ANIME') || cat.includes('MANGA')) return '⛩️';
            if (cat.includes('PREMIUM') || cat.includes('VIP')) return '💎';

            // Kalau bener-bener gak tau
            return '📂';
        };

        // 3. BACA COMMANDS
        const commandFiles = fs.readdirSync(__dirname).filter(file => file.endsWith('.js'));
        const categories = {};

        for (const file of commandFiles) {
            try {
                const cmdModule = require(path.join(__dirname, file));
                if (cmdModule.metadata) {
                    const meta = cmdModule.metadata;
                    // Bikin array kategori kalau belum ada
                    if (!categories[meta.category]) {
                        categories[meta.category] = [];
                    }
                    meta.commands.forEach(c => {
                        categories[meta.category].push(`- *${c.command}* : ${c.desc}`);
                    });
                }
            } catch (err) {
                console.error(`Gagal baca metadata ${file}:`, err);
            }
        }

        // 4. RAKIT TEXT (DENGAN LOGIKA PINTAR)
        // Kita urutkan kategori prioritas dulu biar rapi di atas
        const priorityOrder = ['KEUANGAN', 'DOWNLOADER', 'MEDIA', 'AI', 'SYSTEM'];

        // Loop Priority dulu
        priorityOrder.forEach(cat => {
            if (categories[cat]) {
                const icon = getSmartIcon(cat);
                menuText += `${icon} *${cat}*\n${categories[cat].join('\n')}\n\n`;
                delete categories[cat]; // Hapus dari list biar gak dobel
            }
        });

        // Loop Sisanya (Kategori baru apapun akan diproses di sini)
        for (const cat in categories) {
            const icon = getSmartIcon(cat); // 👈 Disini dia nebak iconnya
            menuText += `${icon} *${cat}*\n${categories[cat].join('\n')}\n\n`;
        }

        menuText += `_Gunakan dengan bijak ya Bang ${namaPengirim}!_ ☕`;
        return client.sendMessage(chatDestination, menuText);
    }
};

module.exports.metadata = {
    category: "SYSTEM",
    commands: [
        { command: '!menu', desc: 'Tampilkan menu otomatis' },
        { command: '!cekid', desc: 'Cek ID info' }
    ]
};