const fs = require('fs');
const path = require('path');

module.exports = async (client, msg, text, senderId, namaPengirim) => {
    const chatDestination = msg.fromMe ? msg.to : msg.from;

    // --- FITUR 1: CEK ID (!CEKID) ---
    if (text === '!cekid') {
        return client.sendMessage(chatDestination, `🆔 ID Terdeteksi: \`${senderId}\`\n👤 User: ${namaPengirim || 'Gak Dikenal'}`);
    }

    // --- FITUR 2: MENU OTOMATIS (!HELP / !MENU) ---
    if (text === '!help' || text === '!menu') {
        let menuText = `🤖 *MENU BOT KEUANGAN & AI* 🤖\n_Auto-Generated by System_\n\n`;

        // 1. BACA SEMUA FILE DI FOLDER COMMANDS
        const commandFiles = fs.readdirSync(__dirname).filter(file => file.endsWith('.js'));

        // 2. KUMPULKAN KATEGORI
        const categories = {};

        for (const file of commandFiles) {
            try {
                // Import file command secara dinamis
                const cmdModule = require(path.join(__dirname, file));

                // Cek apakah file punya "Label Metadata"
                if (cmdModule.metadata) {
                    const meta = cmdModule.metadata;

                    if (!categories[meta.category]) {
                        categories[meta.category] = [];
                    }

                    // Masukin daftar command ke kategori
                    meta.commands.forEach(c => {
                        categories[meta.category].push(`- *${c.command}* : ${c.desc}`);
                    });
                }
            } catch (err) {
                console.error(`Gagal baca metadata ${file}:`, err);
            }
        }

        // 3. RAKIT TEXT MENU
        // Urutan prioritas kategori (biar rapi)
        const order = ['KEUANGAN', 'AI', 'SYSTEM', 'LAINNYA'];

        // Loop sesuai urutan prioritas dulu
        order.forEach(cat => {
            if (categories[cat]) {
                menuText += `📂 *${cat}*\n${categories[cat].join('\n')}\n\n`;
                delete categories[cat]; // Hapus biar gak dobel
            }
        });

        // Loop sisanya (kalo ada kategori baru yg lu buat nanti)
        for (const cat in categories) {
            menuText += `Vr *${cat}*\n${categories[cat].join('\n')}\n\n`;
        }

        menuText += `_Gunakan dengan bijak ya Bang ${namaPengirim}!_ ☕`;
        return client.sendMessage(chatDestination, menuText);
    }
};

// --- LABEL METADATA (BIAR DIA BISA NAMPILIN DIRINYA SENDIRI) ---
module.exports.metadata = {
    category: "SYSTEM",
    commands: [
        { command: '!menu', desc: 'Tampilkan daftar ini' },
        { command: '!cekid', desc: 'Cek ID WhatsApp' }
    ]
};