const fs = require('fs');
const path = require('path');
const config = require('../config');
const db = require('../lib/database');
const logger = require('../lib/logger');
const eventBus = require('../lib/eventBus');
const { COMMAND_COOLDOWN_MS, OBSERVER_DEBOUNCE_MS } = require('../lib/constants');

// ============================================================
// 🔄 PRE-LOAD COMMANDS (SEKALIGUS SCAN PUBLIC COMMAND)
// ============================================================
const commands = new Map();
const publicCommands = [];

const commandFiles = fs.readdirSync(path.join(__dirname, '../commands')).filter(file => file.endsWith('.js'));

for (const file of commandFiles) {
    try {
        const module = require(`../commands/${file}`);
        if (module.metadata && module.metadata.commands) {
            module.metadata.commands.forEach(cmd => {
                const handler = module.interact || module;
                commands.set(cmd.command, handler);

                if (cmd.isPublic) {
                    publicCommands.push(cmd.command.toLowerCase());
                }
            });
        }
    } catch (e) { logger.error(`Skip ${file}: ${e.message}`); }
}
logger.info(`${commands.size} Commands Loaded!`);

const cooldowns = new Map();
const observerCooldowns = new Map();

// ============================================================
// PIPELINE STAGES
// ============================================================

function filterStatus(_ctx, msg) {
    if (msg.isStatus || msg.type === 'e2e_notification' || msg.type === 'call_log') return false;
}

function parseContext(ctx, msg) {
    const body = msg.body || '';
    let rawSenderId = msg.author || msg.from;

    if (msg.fromMe && ctx.client.info && ctx.client.info.wid) {
        rawSenderId = ctx.client.info.wid._serialized;
    }

    let senderId = rawSenderId;
    if (senderId.includes(':')) {
        senderId = senderId.substring(0, senderId.indexOf(':')) + senderId.substring(senderId.indexOf('@'));
    }

    const isGroup = msg.from.includes('@g.us');
    let namaPengirim = config.users[senderId];
    const isRegisteredUser = !!namaPengirim;
    if (!namaPengirim) namaPengirim = msg.pushName || 'Guest';

    const cleanBody = body.trim();
    const isBotResponse = msg.fromMe && (
        /^\p{Extended_Pictographic}/u.test(cleanBody) ||
        cleanBody.includes('[DEBUG]') ||
        cleanBody.includes('SYSTEM ONLINE') ||
        cleanBody.includes('Generated by') ||
        cleanBody.includes('[MEMORY SAVED]')
    );

    const isPublicCommand = publicCommands.some(cmd => body.toLowerCase().startsWith(cmd));
    const isLink = body.match(/(https?:\/\/[^\s]+)/g);
    const isDownloaderLink = isLink && (
        body.toLowerCase().includes('tiktok.com') ||
        body.toLowerCase().includes('facebook.com') ||
        body.toLowerCase().includes('instagram.com')
    );

    ctx.body = body;
    ctx.rawSenderId = rawSenderId;
    ctx.senderId = senderId;
    ctx.isGroup = isGroup;
    ctx.namaPengirim = namaPengirim;
    ctx.isRegisteredUser = isRegisteredUser;
    ctx.cleanBody = cleanBody;
    ctx.isBotResponse = isBotResponse;
    ctx.isPublicCommand = isPublicCommand;
    ctx.isDownloaderLink = isDownloaderLink;
}

function filterBotResponse(ctx) {
    if (ctx.isBotResponse) return false;
}

function logMessage(ctx, msg) {
    if (!ctx.isGroup && ctx.cleanBody.length > 0) {
        db.query(
            'INSERT INTO full_chat_logs (nama_pengirim, pesan, is_forwarded) VALUES (?, ?, ?)',
            [ctx.namaPengirim, msg.body, msg.isForwarded ? 1 : 0]
        ).catch((e) => logger.error('Chat log insert failed:', e.message));

        logger.info(`[${ctx.namaPengirim}]: ${msg.body}`);
    }
}

function filterGuest(ctx) {
    if (!ctx.isRegisteredUser && !ctx.isPublicCommand && !ctx.isDownloaderLink) {
        logger.debug(`[GUEST DROP] ID: ${ctx.senderId} | Nama: ${ctx.namaPengirim}`);
        return false;
    }
}

async function handleCommand(ctx, client, msg) {
    if (ctx.body.startsWith('!') || ctx.body.startsWith('/')) {
        const args = ctx.body.trim().split(/ +/);
        const commandName = args[0].toLowerCase();

        if (commands.has(commandName)) {
            if (cooldowns.has(ctx.rawSenderId)) {
                if (Date.now() < cooldowns.get(ctx.rawSenderId) + COMMAND_COOLDOWN_MS) return false;
            }

            const handler = commands.get(commandName);
            try {
                await handler(client, msg, args, ctx.rawSenderId, ctx.namaPengirim, ctx.body);
            } catch (e) {
                logger.error(`Cmd Error [${commandName}]: ${e.message}`);
            }

            cooldowns.set(ctx.rawSenderId, Date.now());
            setTimeout(() => cooldowns.delete(ctx.rawSenderId), COMMAND_COOLDOWN_MS);
            return false;
        }
    }
}

async function handleAutoDownload(ctx, client, msg) {
    if (ctx.isDownloaderLink) {
        if (msg.hasMedia || ctx.isGroup) return;

        const autoHandler = commands.get('(auto detect)') || commands.get('(Auto Detect)');
        if (autoHandler) {
            logger.info('Link Download Terdeteksi!');
            await autoHandler(client, msg, [], ctx.rawSenderId, ctx.namaPengirim, ctx.body);
            return false;
        }
    }
}

function handleObserver(ctx, client, msg) {
    if (!ctx.body.startsWith('!') && !ctx.body.startsWith('/') && !ctx.isGroup && ctx.isRegisteredUser) {
        const lastObserve = observerCooldowns.get(ctx.rawSenderId) || 0;
        if (Date.now() - lastObserve > OBSERVER_DEBOUNCE_MS) {
            observerCooldowns.set(ctx.rawSenderId, Date.now());
            setTimeout(() => observerCooldowns.delete(ctx.rawSenderId), OBSERVER_DEBOUNCE_MS);
            eventBus.emit('message:incoming', { client, msg, namaPengirim: ctx.namaPengirim });
        }
    }
}

// ============================================================
// MAIN HANDLER (PIPELINE)
// ============================================================
const messageHandler = async (client, msg) => {
    try {
        const ctx = {};

        const stages = [
            () => filterStatus(ctx, msg),
            () => parseContext(ctx, msg),
            () => filterBotResponse(ctx),
            () => logMessage(ctx, msg),
            () => filterGuest(ctx),
            (c) => handleCommand(c, client, msg),
            (c) => handleAutoDownload(c, client, msg),
            (c) => handleObserver(c, client, msg),
        ];

        for (const stage of stages) {
            const result = await stage(ctx);
            if (result === false) return;
        }
    } catch (error) {
        logger.error('Handler Fatal Error:', error.message);
    }
};

module.exports = messageHandler;
module.exports.commands = commands;
