const fs = require('fs');
const path = require('path');
const { observe } = require('../commands/ai');
const config = require('../config');
const db = require('../lib/database');
const logger = require('../lib/logger');

// ============================================================
// 🔄 PRE-LOAD COMMANDS (SEKALIGUS SCAN PUBLIC COMMAND)
// ============================================================
const commands = new Map();
const publicCommands = [];

const commandFiles = fs.readdirSync(path.join(__dirname, '../commands')).filter(file => file.endsWith('.js'));

for (const file of commandFiles) {
    try {
        const module = require(`../commands/${file}`);
        if (module.metadata && module.metadata.commands) {
            module.metadata.commands.forEach(cmd => {
                const handler = module.interact || module;
                commands.set(cmd.command, handler);

                if (cmd.isPublic) {
                    publicCommands.push(cmd.command.toLowerCase());
                }
            });
        }
    } catch (e) { logger.error(`Skip ${file}: ${e.message}`); }
}
logger.info(`${commands.size} Commands Loaded!`);

const cooldowns = new Map();
const observerCooldowns = new Map(); // debounce observer: 10 detik per user

// ============================================================
// 🤖 FUNGSI UTAMA HANDLER
// ============================================================
const messageHandler = async (client, msg) => {
    try {
        if (msg.isStatus || msg.type === 'e2e_notification' || msg.type === 'call_log') return;

        const body = msg.body || "";
        
        // TETAP SIMPAN rawSenderId BUAT DI-PASSING KE COMMAND NANTI
        let rawSenderId = msg.author || msg.from;

        // 🔥 FIX SELF-BOT: Kalau pesan dari kita sendiri, paksa pake ID kita!
        if (msg.fromMe && client.info && client.info.wid) {
            rawSenderId = client.info.wid._serialized;
        }

        // 🔥 PEMBERSIH ID SAKTI (Babat Habis Multi-Device @c.us / @lid)
        let senderId = rawSenderId;
        if (senderId.includes(':')) {
            // Motong bagian ":20" dan nyambungin balik sama "@lid" atau "@c.us"
            senderId = senderId.substring(0, senderId.indexOf(':')) + senderId.substring(senderId.indexOf('@'));
        }

        const isGroup = msg.from.includes('@g.us');

        // ==========================================
        // 🛑 1. THE GATEKEEPER (SMART FILTER)
        // ==========================================
        // Cek apakah ID bersih ada di config
        let namaPengirim = config.users[senderId];
        const isRegisteredUser = !!namaPengirim; // true kalau ada di config

        // Kalau terpaksa banget masih gak ketemu
        if (!namaPengirim) {
            namaPengirim = msg.pushName || "Guest";
        }

        const isPublicCommand = publicCommands.some(cmd => body.toLowerCase().startsWith(cmd));
        const isLink = body.match(/(https?:\/\/[^\s]+)/g);
        const isDownloaderLink = isLink && (
            body.toLowerCase().includes('tiktok.com') ||
            body.toLowerCase().includes('facebook.com') ||
            body.toLowerCase().includes('instagram.com')
        );

        // USIR GUEST JIKA BUKAN PUBLIC COMMAND / DOWNLOADER
        if (!isRegisteredUser) {
            if (!isPublicCommand && !isDownloaderLink) {
                return; 
            }
        }

        // ============================================================
        // 🧹 2. CLEANER LOG (FILTER SAMPAH BOT)
        // ============================================================
        const cleanBody = body.trim();
        const isBotResponse = msg.fromMe && (
            /^\p{Extended_Pictographic}/u.test(cleanBody) || 
            cleanBody.includes('[DEBUG]') ||
            cleanBody.includes('SYSTEM ONLINE') ||
            cleanBody.includes('Generated by') ||
            cleanBody.includes('[MEMORY SAVED]')
        );

        if (isBotResponse) return;

        logger.info(`[${namaPengirim}]: ${body}`);

        // ============================================================
        // 💾 3. DATABASE LOGGING (async — gak nunggu)
        // ============================================================
        db.query(
            "INSERT INTO full_chat_logs (nama_pengirim, pesan, is_forwarded) VALUES (?, ?, ?)",
            [namaPengirim, body, msg.isForwarded ? 1 : 0]
        ).catch(() => {});

        // ============================================================
        // 🎮 4. HANDLE COMMANDS
        // ============================================================
        if (body.startsWith('!') || body.startsWith('/')) {
            const args = body.trim().split(/ +/);
            const commandName = args[0].toLowerCase();

            if (commands.has(commandName)) {
                if (cooldowns.has(rawSenderId)) {
                    if (Date.now() < cooldowns.get(rawSenderId) + 1500) return;
                }
                
                const handler = commands.get(commandName);
                try {
                    // SEKARANG rawSenderId AMAN DIPAKE DISINI
                    await handler(client, msg, args, rawSenderId, namaPengirim, body);
            } catch (e) { 
                logger.error(`Cmd Error [${commandName}]: ${e.message}`); 
            }
                
                cooldowns.set(rawSenderId, Date.now());
                setTimeout(() => cooldowns.delete(rawSenderId), 1500);
                return;
            }
        }

        // ============================================================
        // 📥 5. AUTO DOWNLOADER
        // ============================================================
        if (isDownloaderLink) {
            if (msg.hasMedia || isGroup) return;

            const autoHandler = commands.get('(auto detect)') || commands.get('(Auto Detect)');
            if (autoHandler) {
                logger.info(`Link Download Terdeteksi!`);
                await autoHandler(client, msg, [], rawSenderId, namaPengirim, body);
                return;
            }
        }

        // ============================================================
        // 🧠 6. AI OBSERVER (debounce: 10 detik per user)
        // ============================================================
        if (!body.startsWith('!') && !body.startsWith('/') && !isGroup && isRegisteredUser) {
            const lastObserve = observerCooldowns.get(rawSenderId) || 0;
            if (Date.now() - lastObserve > 10000) {
                observerCooldowns.set(rawSenderId, Date.now());
                setTimeout(() => observerCooldowns.delete(rawSenderId), 10000);
                observe(client, msg, namaPengirim).catch((e) => {
                    logger.error("Observer Fail:", e.message);
                });
            }
        }

    } catch (error) {
        logger.error("Handler Fatal Error:", error.message);
    }
};

module.exports = messageHandler;
module.exports.commands = commands;