const fs = require('fs');
const path = require('path');
const { observe } = require('../commands/ai');
const config = require('../config');
const db = require('../lib/database');

// ============================================================
// 🔄 PRE-LOAD COMMANDS (SEKALIGUS SCAN PUBLIC COMMAND)
// ============================================================
const commands = new Map();
const publicCommands = [];

const commandFiles = fs.readdirSync(path.join(__dirname, '../commands')).filter(file => file.endsWith('.js'));

for (const file of commandFiles) {
    try {
        const module = require(`../commands/${file}`);
        if (module.metadata && module.metadata.commands) {
            module.metadata.commands.forEach(cmd => {
                const handler = module.interact || module;
                commands.set(cmd.command, handler);

                // Cek Tanda 'isPublic'
                if (cmd.isPublic) {
                    publicCommands.push(cmd.command.toLowerCase());
                }
            });
        }
    } catch (e) { console.error(`Skip ${file}: ${e.message}`); }
}
console.log(`✅ ${commands.size} Commands Loaded!`);

const cooldowns = new Map();

// ============================================================
// 🤖 FUNGSI UTAMA HANDLER
// ============================================================
const messageHandler = async (client, msg) => {
    try {
        // Skip status & notif sistem
        if (msg.isStatus || msg.type === 'e2e_notification' || msg.type === 'call_log') return;

        const body = msg.body || "";
        let senderId = msg.author || msg.from;

        // 🔥 PEMBERSIH ID SAKTI (Babat Habis Multi-Device @c.us / @lid)
        if (senderId.includes(':')) {
            // Motong bagian ":20" dan nyambungin balik sama "@lid" atau "@c.us"
            senderId = senderId.substring(0, senderId.indexOf(':')) + senderId.substring(senderId.indexOf('@'));
        }

        const isGroup = msg.from.includes('@g.us');

        // ============================================================
        // 🛑 1. THE GATEKEEPER (SMART FILTER - AUTO PUBLIC)
        // ============================================================

        let namaPengirim = config.users[senderId];
        let isRegisteredUser = false;
        const daftarUser = Object.keys(config.users);

        // Cari nomor murni di dalam string ID yang aneh-aneh
        for (const idConfig of daftarUser) {
            const nomorMurni = idConfig.split('@')[0].split(':')[0]; // Ambil cuma angkanya (misal: 6289...)
            
            if (rawSenderId.includes(nomorMurni)) {
                namaPengirim = config.users[idConfig];
                isRegisteredUser = true;
                break;
            }
        }

        // Kalau beneran gak ketemu di config, baru jadiin Guest
        if (!namaPengirim) {
            namaPengirim = msg.pushName || "Guest";
        }

        // ============================================================
        // 🛑 2. THE GATEKEEPER (SMART FILTER - AUTO PUBLIC)
        // ============================================================
        const isPublicCommand = publicCommands.some(cmd => body.toLowerCase().startsWith(cmd));
        
        const isLink = body.match(/(https?:\/\/[^\s]+)/g);
        const isDownloaderLink = isLink && (
            body.toLowerCase().includes('tiktok.com') ||
            body.toLowerCase().includes('facebook.com') ||
            body.toLowerCase().includes('instagram.com')
        );

        // JIKA GUEST (BUKAN OWNER/ADMIN)
        if (!isRegisteredUser) {
            // Kalau bukan command publik & bukan link download -> CUEKIN AJA (Usir)
            if (!isPublicCommand && !isDownloaderLink) {
                return;
            }
        }

        // ============================================================
        // 🧹 3. CLEANER LOG (FILTER SAMPAH BOT)
        // ============================================================
        // Jangan log pesan bot sendiri (kecuali bot dipanggil paksa)
        const isBotResponse = msg.fromMe && (
            /^\p{Extended_Pictographic}/u.test(cleanBody) || // Diawali Emoji
            cleanBody.includes('[DEBUG]') ||
            cleanBody.includes('SYSTEM ONLINE') ||
            cleanBody.includes('Generated by') || // 👈 Tambahan dari filter AI
            cleanBody.includes('[MEMORY SAVED]')
        );

        if (isBotResponse) return;

        // Log ke Terminal
        console.log(`💬 [${namaPengirim}]: ${body}`);

        // ============================================================
        // 💾 4. DATABASE LOGGING
        // ============================================================
        try {
            await db.query(
                "INSERT INTO full_chat_logs (nama_pengirim, pesan, is_forwarded) VALUES (?, ?, ?)",
                [namaPengirim, body, msg.isForwarded ? 1 : 0]
            );
        } catch (err) { /* Abaikan error DB ringan */ }

        // ============================================================
        // 🎮 5. HANDLE COMMANDS (! atau /)
        // ============================================================
        if (body.startsWith('!') || body.startsWith('/')) {
            const args = body.trim().split(/ +/);
            const commandName = args[0].toLowerCase();

            if (commands.has(commandName)) {
                // Rate Limiter / Cooldown
                if (cooldowns.has(rawSenderId)) {
                    if (Date.now() < cooldowns.get(rawSenderId) + 1500) return;
                }
                
                const handler = commands.get(commandName);
                
                try {
                    // Oper namaPengirim yang udah bener ke Command!
                    await handler(client, msg, args, rawSenderId, namaPengirim, body);
                } catch (e) { 
                    console.error(`Cmd Error [${commandName}]: ${e.message}`); 
                }
                
                cooldowns.set(rawSenderId, Date.now());
                setTimeout(() => cooldowns.delete(rawSenderId), 1500);
                return;
            }
        }

        // ============================================================
        // 📥 6. AUTO DOWNLOADER (Tanpa ngetik !tiktok)
        // ============================================================
        if (isDownloaderLink) {
            if (msg.hasMedia || isGroup) return;

            const autoHandler = commands.get('(auto detect)') || commands.get('(Auto Detect)');
            if (autoHandler) {
                console.log(`🔗 Link Download Terdeteksi!`);
                await autoHandler(client, msg, [], rawSenderId, namaPengirim, body);
                return;
            }
        }

        // ============================================================
        // 🧠 7. AI OBSERVER (Mata-Mata)
        // ============================================================
        // Syarat: Bukan command, Bukan Grup, Harus User Terdaftar (Owner)
        if (!body.startsWith('!') && !body.startsWith('/') && !isGroup && isRegisteredUser) {
            observe(client, msg, namaPengirim).catch((e) => {
                console.error("Observer Fail:", e.message);
            });
        }

    } catch (error) {
        console.error("Handler Fatal Error:", error);
    }
};

module.exports = messageHandler;
module.exports.commands = commands;