module.exports = {
    // Cooldowns
    COMMAND_COOLDOWN_MS: 1500,
    OBSERVER_DEBOUNCE_MS: 10000,

    // Rate limits
    AI_RATE_WINDOW_MS: 60000,
    AI_RATE_MAX: 5,
    DOWNLOAD_RATE_WINDOW_MS: 60000,
    DOWNLOAD_RATE_MAX: 3,

    // Downloads
    DOWNLOAD_TIMEOUT_MS: 30000,
    DOWNLOAD_MAX_RETRIES: 2,
    DOWNLOAD_RETRY_DELAY_MS: 1000,

    // Memory
    MEMORY_MAX_PER_USER: 500,
    MEMORY_LIST_LIMIT: 10,
    MEMORY_DISPLAY_LIMIT: 10,

    // Chat
    CHAT_HISTORY_LIMIT: 15,
    STATS_RECENT_MSGS: 100,

    // Commands
    LOG_QUERY_DEFAULT_LIMIT: 20,
    LOG_QUERY_MAX_LIMIT: 200,

    // Events
    EVENT_CHECK_HOUR: 7,
    EVENT_CHECK_MINUTE: 0,
    EVENT_CHECK_SECOND_MAX: 2,

    // Reminders
    OVERDUE_EXPIRY_MINUTES: 60,
    OVERDUE_STAGGER_MS: 2000,

    // Dashboard
    SESSION_MAX_AGE_MS: 24 * 60 * 60 * 1000, // 24 hours
};
