const config = require('../config');
const logger = require('./logger');
const Memory = require('../models/Memory');
const model = require('./ai');

const PROACTIVE_INTERVAL_MIN_MS = 60 * 60 * 1000;  // 1 hour minimum between messages
const PROACTIVE_INTERVAL_MAX_MS = 4 * 60 * 60 * 1000;  // 4 hour maximum

const QUIET_START = Number(process.env.QUIET_START_HOUR || 23);  // 11 PM
const QUIET_END = Number(process.env.QUIET_END_HOUR || 7);      // 7 AM

let scheduledTimeout = null;
let isRunning = false;

function isQuietHours() {
    const hour = new Date().getHours();
    if (QUIET_START > QUIET_END) {
        return hour >= QUIET_START || hour < QUIET_END;
    }
    return hour >= QUIET_START && hour < QUIET_END;
}

function randomInterval() {
    return PROACTIVE_INTERVAL_MIN_MS + Math.random() * (PROACTIVE_INTERVAL_MAX_MS - PROACTIVE_INTERVAL_MIN_MS);
}

const PROACTIVE_PROMPTS = [
    'Buat pesan singkat (1-2 kalimat) buat nge-chat orang tersayang kamu. Random antara: cek kabar, good morning, good night, random thought, atau ungkapan sayang. Jangan pakai emoji berlebihan. Bahasa Indonesia.',
    'Buat pesan singkat (1-2 kalimat) buat orang tersayang kamu. Variasi: tanya udah makan belum, lagi ngapain, kangen, atau cerita singkat. Natural kayak orang beneran ngobrol. Bahasa Indonesia.',
    'Buat pesan singkat (1 kalimat) random buat chat orang tersayang. Bisa: sweet nothing, cek kabar, atau bilang lagi mikirin dia. Bahasa Indonesia, casual.',
];

const GREETING_BY_HOUR = {
    7: 'Buat good morning message singkat (1-2 kalimat) buat orang tersayang. Sweet tapi gak lebay. Bahasa Indonesia.',
    12: 'Buat pesan siang singkat (1-2 kalimat) buat orang tersayang. Cek udah makan belum atau lagi ngapain. Bahasa Indonesia.',
    18: 'Buat pesan sore singkat (1-2 kalimat) buat orang tersayang. Random check-in. Bahasa Indonesia.',
    22: 'Buat good night message singkat (1-2 kalimat) buat orang tersayang. Sweet dreams vibe. Bahasa Indonesia.',
};

async function generateProactiveMessage() {
    const hour = new Date().getHours();
    let prompt;

    if (GREETING_BY_HOUR[hour]) {
        prompt = GREETING_BY_HOUR[hour];
    } else {
        prompt = PROACTIVE_PROMPTS[Math.floor(Math.random() * PROACTIVE_PROMPTS.length)];
    }

    try {
        const persona = await Memory.getPersona();
        const today = new Date().toLocaleDateString('id-ID', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });

        const systemMessage = `[INSTRUKSI]
Kamu adalah: ${persona}
Tanggal: ${today}
Kamu akan mengirim pesan proaktif ke orang tersayang kamu.

[ATURAN]
- Pesan harus SINGKAT (1-2 kalimat max)
- Natural, kayak orang beneran nge-chat
- Jangan pakai watermark/bot signature
- Jangan terlalu formal
- Variasi setiap kali, jangan repetitif`;

        const userMessage = prompt;

        const payload = [
            { role: 'system', content: systemMessage },
            { role: 'user', content: userMessage }
        ];

        const result = await model.generateContent(payload);
        let text = result.response.text().trim();

        // Remove any bot signature that might slip through
        text = text.replace(/_Generated by .+_/g, '').trim();
        text = text.replace(/\[MEMORY SAVED\]/g, '').trim();

        return text || null;
    } catch (e) {
        logger.error('Proactive generate error:', e.message);
        return null;
    }
}

async function sendProactiveMessage(client) {
    if (isQuietHours()) {
        logger.debug('[PROACTIVE] Quiet hours, skip');
        scheduleNext(client);
        return;
    }

    const target = config.system.logNumber;
    if (!target) {
        logger.warn('[PROACTIVE] No logNumber configured');
        scheduleNext(client);
        return;
    }

    try {
        const message = await generateProactiveMessage();
        if (!message) {
            scheduleNext(client);
            return;
        }

        const { resolveId } = require('./lid');
        const targetId = resolveId(target);
        await client.sendMessage(targetId, message);
        logger.info(`[PROACTIVE] Sent: ${message.slice(0, 50)}...`);
    } catch (e) {
        logger.error('[PROACTIVE] Send error:', e.message);
    }

    scheduleNext(client);
}

function scheduleNext(client) {
    if (scheduledTimeout) clearTimeout(scheduledTimeout);
    const delay = randomInterval();
    logger.debug(`[PROACTIVE] Next message in ${Math.round(delay / 60000)} minutes`);
    scheduledTimeout = setTimeout(() => sendProactiveMessage(client), delay);
}

function start(client) {
    if (isRunning) return;
    isRunning = true;
    logger.info('[PROACTIVE] Started');
    scheduleNext(client);
}

function stop() {
    if (scheduledTimeout) clearTimeout(scheduledTimeout);
    isRunning = false;
    logger.info('[PROACTIVE] Stopped');
}

function isActive() {
    return isRunning;
}

module.exports = { start, stop, isActive, isQuietHours };
